# Site settings
title            : 'SAS-R'
email            : vincent.knight@gmail.com
description      : "Class website for MAT013"
baseurl          : "/SAS-R"
url              : "http://drvinceknight.github.io"
github_username  : "drvinceknight"
twitter_username : "@drvinceknight"
plus_username    : "+VincentKnight"
blogurl          : "http://drvinceknight.github.io/unpeudemath/"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
